version: '3.8'

services:

  vault:
    image: vault:latest
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - '8200:8200'
    environment:
      - VAULT_ADDR=http://localhost:8200
      - VAULT_API_ADDR=http://localhost:8200
      - VAULT_ADDRESS=http://localhost:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json

  metis_db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=metis
      - POSTGRES_PASSWORD=metis
      - POSTGRES_DB=metis_db
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql


  metis_app:
    image: metis-app:latest
    container_name: metis-app
    hostname: metis-app
    build: .
    restart: on-failure
    depends_on:
      - metis_db
    ports:
      - '5000:5000'

volumes:
  db_volume:
    #external: true mean volume is created outside the container with docker volume create
